[project]
name = "mcp-server-neo4j"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
    "neo4j>=6.0.3",
]
